### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by chegewara** [chegewara/esp32-snippets#7]
- [x] - bugfix BLEAdvertisingDevice line 140
- [x] - fix HID class for macOS (add permissions)
- [x] - fix max mtu size to 517 (BLECharacteristic)
- [x] - add BLEserver::connect, (esp_ble_gatts_open)		
- [x] - fix gattc_open remote address type						<-- bug in esp-idf?
- [ ] - add advertising type (direct adv)							<-- bug in esp-idf?
- [ ] - 6.3.1 Notifications and Indications While Disconnected - BT core page 2279
- [ ] - add multi server connect
- [x] - add multi client connect
- [ ] - bugfix BLERemoteService (getCharacteristicsByHandle()),				<-- WIP
- [ ] - add midi over ble example,					
- [ ] - add to BLEClient std:map servicesByHandle	
- [ ] - fix semaphore wait in BLECharacteristic->notify() and more
- [x] - 2.5.2 Attribute Caching - page 2227, is it driver or application implemented?	
- [x] - add search thru nvs cache
- [x] -- services	
- [x] -- characteristics
- [x] -- descriptors	
- [x] - fix BLEUUID(std::string)
- [ ] - add SCCDesc(0x2903) if characteristic can broadcast - page 2240
- [ ] - fix remotecharacteristic readValue get outdated data		<-- semaphore issue related
- [x] - bugfix BLEAdvertisedDevice::parseAdvertisement to parse adv+scnResp length		<--
- [x] - BLEScan memory leak
- [ ] - fix bug setByHandle() in BLEServer.cpp
- [x] - add random mac address generator
